language: node_js
node_js: stable

sudo: false

install: true # yarn bug

branch:
  only:
    - master

cache:
    directories:
      - node_modules

before_install:
  - npm install -g typings
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


script:
  - typings install
  - npm run test:ci